# Generated by Django 4.2.7 on 2023-12-02 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iblog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categpry",
            new_name="Category",
        ),
    ]
